package dev.schoenberg.evergore.protocolParser.domain;

import static dev.schoenberg.evergore.protocolParser.domain.EvergoreItem.Category.*;
import static dev.schoenberg.evergore.protocolParser.domain.EvergoreItem.Recipe.*;
import static java.util.Arrays.*;

import java.util.*;

public enum EvergoreItem {
	BESCHLAEGE("Beschläge", 500, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	BOGENSALBE("Bogensalbe", 80, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	DRACHENZUNDER("Drachenzunder", 150, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	DRACHINSCHNEIDEN("Drachinschneiden", 500, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	EDELMOERTEL("Edelmörtel", 180, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	ELBENHAAR("Elbenhaar", 200, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	ERDENBLUT("Erdenblut", 500, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	FEDERN("Federn", 25, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	GLASZWIRN("Glaszwirn", 150, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	GRANITHARZ("Granitharz", 150, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	GRIFFBAND("Griffband", 500, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	HARZ("Harz", 100, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	KRISTALLAT("Kristallat", 150, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	LEDERFETT("Lederfett", 80, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	LEDERNIETEN("Ledernieten", 200, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	MAGIESPLITTER("Magiesplitter", 60, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	MOERTEL("Mörtel", 80, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	NIETEN("Nieten", 500, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	NAEHGARN("Nähgarn", 80, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	PFEILHARZ("Pfeilharz", 150, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	PHASENKRAUT("Phasenkraut", 200, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	SALZ("Salz", 100, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	SCHLEIFSTEIN("Schleifstein", 200, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	SCHMIEDEOEL("Schmiedeöl", 80, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	SCHUTZPOLSTER("Schutzpolster", 200, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	STEINKOHLE("Steinkohle", 100, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	VULKANDRAHT("Vulkandraht", 500, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	WATTIERUNG("Wattierung", 200, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	ZWIRN("Zwirn", 100, HANDWERKSMATERIAL, NOT_CRAFTABLE),
	BAUMWOLLE("Baumwolle", 60, JAGDBEUTEN, NOT_CRAFTABLE),
	DRACHENHAUT("Drachenhaut", 120, JAGDBEUTEN, NOT_CRAFTABLE),
	HARTPELZ("Hartpelz", 60, JAGDBEUTEN, NOT_CRAFTABLE),
	LEINEN("Leinen", 20, JAGDBEUTEN, NOT_CRAFTABLE),
	MAGIESTAUB("Magiestaub", 20, JAGDBEUTEN, NOT_CRAFTABLE),
	MONDSTAUB("Mondstaub", 90, JAGDBEUTEN, NOT_CRAFTABLE),
	PELZE("Pelze", 40, JAGDBEUTEN, NOT_CRAFTABLE),
	RIESENHAUT("Riesenhaut", 90, JAGDBEUTEN, NOT_CRAFTABLE),
	SCHATTENSTAUB("Schattenstaub", 60, JAGDBEUTEN, NOT_CRAFTABLE),
	SEIDE("Seide", 90, JAGDBEUTEN, NOT_CRAFTABLE),
	STERNENSTAUB("Sternenstaub", 120, JAGDBEUTEN, NOT_CRAFTABLE),
	TODESSTAUB("Todesstaub", 40, JAGDBEUTEN, NOT_CRAFTABLE),
	WEICHPELZE("Weichpelze", 20, JAGDBEUTEN, NOT_CRAFTABLE),
	WOLLE("Wolle", 40, JAGDBEUTEN, NOT_CRAFTABLE),
	AETHERFAEDEN("Ätherfäden", 120, JAGDBEUTEN, NOT_CRAFTABLE),
	ADAMANTERZ("Adamanterz", 90, ROHSTOFFE, NOT_CRAFTABLE),
	BIRKENHOLZ("Birkenholz", 40, ROHSTOFFE, NOT_CRAFTABLE),
	BUCHENHOLZ("Buchenholz", 20, ROHSTOFFE, NOT_CRAFTABLE),
	EIBENHOLZ("Eibenholz", 120, ROHSTOFFE, NOT_CRAFTABLE),
	EICHENHOLZ("Eichenholz", 60, ROHSTOFFE, NOT_CRAFTABLE),
	EISENERZ("Eisenerz", 40, ROHSTOFFE, NOT_CRAFTABLE),
	ESCHENHOLZ("Eschenholz", 90, ROHSTOFFE, NOT_CRAFTABLE),
	GRANITSTEIN("Granitstein", 90, ROHSTOFFE, NOT_CRAFTABLE),
	KALKSTEIN("Kalkstein", 20, ROHSTOFFE, NOT_CRAFTABLE),
	KUPFERERZ("Kupfererz", 20, ROHSTOFFE, NOT_CRAFTABLE),
	MARMORSTEIN("Marmorstein", 120, ROHSTOFFE, NOT_CRAFTABLE),
	MITHRILERZ("Mithrilerz", 120, ROHSTOFFE, NOT_CRAFTABLE),
	SANDSTEIN("Sandstein", 40, ROHSTOFFE, NOT_CRAFTABLE),
	SCHIEFERSTEIN("Schieferstein", 60, ROHSTOFFE, NOT_CRAFTABLE),
	SORANDILERZ("Sorandilerz", 60, ROHSTOFFE, NOT_CRAFTABLE),
	ADAMANTBARREN("Adamantbarren", 270, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, ADAMANTERZ), new Ingredient(3, DRACHENZUNDER))),
	BAUMWOLLTUCH("Baumwolltuch", 180, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, BAUMWOLLE), new Ingredient(2, GLASZWIRN))),
	BIRKENBRETTER("Birkenbretter", 120, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, BIRKENHOLZ), new Ingredient(2, HARZ))),
	BUCHENBRETTER("Buchenbretter", 60, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, BUCHENHOLZ), new Ingredient(1, HARZ))),
	DRACHENLEDER("Drachenleder", 360, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, DRACHENHAUT), new Ingredient(4, KRISTALLAT))),
	EIBENBRETTER("Eibenbretter", 360, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, EIBENHOLZ), new Ingredient(4, GRANITHARZ))),
	EICHENBRETTER("Eichenbretter", 180, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, EICHENHOLZ), new Ingredient(2, GRANITHARZ))),
	EISENBARREN("Eisenbarren", 120, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, EISENERZ), new Ingredient(2, STEINKOHLE))),
	ESCHENBRETTER("Eschenbretter", 270, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, ESCHENHOLZ), new Ingredient(3, GRANITHARZ))),
	GRANITZIEGEL("Granitziegel", 270, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, GRANITSTEIN), new Ingredient(3, DRACHENZUNDER))),
	HARTLEDER("Hartleder", 180, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, HARTPELZ), new Ingredient(2, KRISTALLAT))),
	KALKZIEGEL("Kalkziegel", 60, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, KALKSTEIN), new Ingredient(1, STEINKOHLE))),
	KUPFERBARREN("Kupferbarren", 60, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, KUPFERERZ), new Ingredient(1, STEINKOHLE))),
	LEDER("Leder", 120, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, PELZE), new Ingredient(2, SALZ))),
	LEINENTUCH("Leinentuch", 60, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, LEINEN), new Ingredient(1, ZWIRN))),
	MARMORZIEGEL("Marmorziegel", 360, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, MARMORSTEIN), new Ingredient(4, DRACHENZUNDER))),
	MITHRILBARREN("Mithrilbarren", 360, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, MITHRILERZ), new Ingredient(4, DRACHENZUNDER))),
	RIESENLEDER("Riesenleder", 270, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, RIESENHAUT), new Ingredient(3, KRISTALLAT))),
	SANDZIEGEL("Sandziegel", 120, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, SANDSTEIN), new Ingredient(2, STEINKOHLE))),
	SCHIEFERZIEGEL("Schieferziegel", 180, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, SCHIEFERSTEIN), new Ingredient(2, DRACHENZUNDER))),
	SEIDENTUCH("Seidentuch", 270, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, SEIDE), new Ingredient(3, GLASZWIRN))),
	SORANDILBARREN("Sorandilbarren", 180, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, SORANDILERZ), new Ingredient(2, DRACHENZUNDER))),
	WEICHLEDER("Weichleder", 60, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, WEICHPELZE), new Ingredient(1, SALZ))),
	WOLLTUCH("Wolltuch", 120, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, WOLLE), new Ingredient(2, ZWIRN))),
	AETHERTUCH("Äthertuch", 360, VERARBEITETE_ROHSTOFFE, new Recipe(5, new Ingredient(5, AETHERFAEDEN), new Ingredient(4, GLASZWIRN))),
	ACHAT("Achat", 500, EDELSTEINE, NOT_CRAFTABLE),
	DIAMANT("Diamant", 5000, EDELSTEINE, NOT_CRAFTABLE),
	JADE("Jade", 3500, EDELSTEINE, NOT_CRAFTABLE),
	JASPIS("Jaspis", 1000, EDELSTEINE, NOT_CRAFTABLE),
	KRISTALL("Kristall", 500, EDELSTEINE, NOT_CRAFTABLE),
	LAPIS("Lapis", 3500, EDELSTEINE, NOT_CRAFTABLE),
	OBSIDIAN("Obsidian", 5000, EDELSTEINE, NOT_CRAFTABLE),
	ONYX("Onyx", 5000, EDELSTEINE, NOT_CRAFTABLE),
	PERLMUTT("Perlmutt", 2000, EDELSTEINE, NOT_CRAFTABLE),
	PYRIT("Pyrit", 500, EDELSTEINE, NOT_CRAFTABLE),
	QUARZ("Quarz", 1000, EDELSTEINE, NOT_CRAFTABLE),
	RUBIN("Rubin", 3500, EDELSTEINE, NOT_CRAFTABLE),
	SAPHIR("Saphir", 2000, EDELSTEINE, NOT_CRAFTABLE),
	SMARAGD("Smaragd", 2000, EDELSTEINE, NOT_CRAFTABLE),
	TOPAS("Topas", 1000, EDELSTEINE, NOT_CRAFTABLE),
	ARBALESTE("Arbaleste", 4000, ARMBRÜSTE, new Recipe(1, new Ingredient(11, BIRKENBRETTER), new Ingredient(16, BOGENSALBE))),
	ARMBRUST("Armbrust", 3000, ARMBRÜSTE, new Recipe(1, new Ingredient(16, BUCHENBRETTER), new Ingredient(12, BOGENSALBE))),
	BALLISTA("Ballista", 6100, ARMBRÜSTE, new Recipe(1, new Ingredient(16, BIRKENBRETTER), new Ingredient(25, BOGENSALBE))),
	BELAGERUNGSARMBRUST("Belagerungsarmbrust", 16300, ARMBRÜSTE,
			new Recipe(1, new Ingredient(20, ESCHENBRETTER), new Ingredient(12, BOGENSALBE), new Ingredient(22, ELBENHAAR))),
	DAEMONENARMBRUST("Dämonenarmbrust", 57300, ARMBRÜSTE,
			new Recipe(1, new Ingredient(52, EIBENBRETTER), new Ingredient(6, BOGENSALBE), new Ingredient(12, ELBENHAAR), new Ingredient(32, GRIFFBAND))),
	HANDARMBRUST("Handarmbrust", 2000, ARMBRÜSTE, new Recipe(1, new Ingredient(11, BUCHENBRETTER), new Ingredient(8, BOGENSALBE))),
	HORNARMBRUST("Hornarmbrust", 12300, ARMBRÜSTE,
			new Recipe(1, new Ingredient(22, EICHENBRETTER), new Ingredient(10, BOGENSALBE), new Ingredient(16, ELBENHAAR))),
	KOLOSSUSARMBRUST("Kolossusarmbrust", 24800, ARMBRÜSTE,
			new Recipe(1, new Ingredient(30, ESCHENBRETTER), new Ingredient(14, BOGENSALBE), new Ingredient(35, ELBENHAAR))),
	KRIEGSARMBRUST("Kriegsarmbrust", 37600, ARMBRÜSTE,
			new Recipe(1, new Ingredient(34, EIBENBRETTER), new Ingredient(4, BOGENSALBE), new Ingredient(8, ELBENHAAR), new Ingredient(21, GRIFFBAND))),
	REPETIERARMBRUST("Repetierarmbrust", 8100, ARMBRÜSTE,
			new Recipe(1, new Ingredient(15, EICHENBRETTER), new Ingredient(8, BOGENSALBE), new Ingredient(10, ELBENHAAR))),
	EINFACHER_WOLLVERBAND("Einfacher Wollverband", 32, BANDAGEN,
			new Recipe(100, new Ingredient(5, WOLLTUCH), new Ingredient(3, LEDER), new Ingredient(12, NAEHGARN))),
	GUTE_BAUMWOLLBINDE("Gute Baumwollbinde", 65, BANDAGEN,
			new Recipe(100, new Ingredient(7, BAUMWOLLTUCH), new Ingredient(4, HARTLEDER), new Ingredient(19, NAEHGARN), new Ingredient(2, PHASENKRAUT))),
	HEILSAMER_SEIDENVERBAND("Heilsamer Seidenverband", 127, BANDAGEN,
			new Recipe(100, new Ingredient(9, SEIDENTUCH), new Ingredient(5, RIESENLEDER), new Ingredient(28, NAEHGARN), new Ingredient(8, PHASENKRAUT))),
	IMPROVISIERTE_LEINENBINDE("Improvisierte Leinenbinde", 16, BANDAGEN,
			new Recipe(100, new Ingredient(5, LEINENTUCH), new Ingredient(3, WEICHLEDER), new Ingredient(6, NAEHGARN))),
	MAGISCHE_AETHERBINDE("Magische Ätherbinde", 257, BANDAGEN,
			new Recipe(100, new Ingredient(14, AETHERTUCH), new Ingredient(7, DRACHENLEDER), new Ingredient(37, NAEHGARN), new Ingredient(17, PHASENKRAUT),
					new Ingredient(3, ERDENBLUT))),
	BIRKEN_DACHKONSTRUKT("Birken-Dachkonstrukt", 6400, BAUTEILE,
			new Recipe(1, new Ingredient(4, SANDZIEGEL), new Ingredient(14, BIRKENBRETTER), new Ingredient(22, HARZ))),
	BIRKEN_STUETZBALKEN("Birken-Stützbalken", 3600, BAUTEILE, new Recipe(1, new Ingredient(10, BIRKENBRETTER), new Ingredient(12, HARZ))),
	BUCHEN_DACHKONSTRUKT("Buchen-Dachkonstrukt", 3200, BAUTEILE,
			new Recipe(1, new Ingredient(4, KALKZIEGEL), new Ingredient(14, BUCHENBRETTER), new Ingredient(11, HARZ))),
	BUCHEN_STUETZBALKEN("Buchen-Stützbalken", 1800, BAUTEILE, new Recipe(1, new Ingredient(10, BUCHENBRETTER), new Ingredient(6, HARZ))),
	EIBEN_DACHKONSTRUKT("Eiben-Dachkonstrukt", 51200, BAUTEILE,
			new Recipe(1, new Ingredient(12, MARMORZIEGEL), new Ingredient(34, EIBENBRETTER), new Ingredient(110, GRANITHARZ))),
	EIBEN_STUETZBALKEN("Eiben-Stützbalken", 28800, BAUTEILE, new Recipe(1, new Ingredient(26, EIBENBRETTER), new Ingredient(62, GRANITHARZ))),
	EICHEN_DACHKONSTRUKT("Eichen-Dachkonstrukt", 12800, BAUTEILE,
			new Recipe(1, new Ingredient(6, SCHIEFERZIEGEL), new Ingredient(17, EICHENBRETTER), new Ingredient(28, GRANITHARZ))),
	EICHEN_STUETZBALKEN("Eichen-Stützbalken", 7200, BAUTEILE, new Recipe(1, new Ingredient(13, EICHENBRETTER), new Ingredient(16, GRANITHARZ))),
	ESCHEN_DACHKONSTRUKT("Eschen-Dachkonstrukt", 25600, BAUTEILE,
			new Recipe(1, new Ingredient(8, GRANITZIEGEL), new Ingredient(22, ESCHENBRETTER), new Ingredient(56, GRANITHARZ))),
	ESCHEN_STUETZBALKEN("Eschen-Stützbalken", 14400, BAUTEILE, new Recipe(1, new Ingredient(17, ESCHENBRETTER), new Ingredient(32, GRANITHARZ))),
	GRANIT_BODENPLATTE("Granit-Bodenplatte", 17600, BAUTEILE, new Recipe(1, new Ingredient(21, GRANITZIEGEL), new Ingredient(32, EDELMOERTEL))),
	GRANIT_MAUERSTUECK("Granit-Mauerstück", 20800, BAUTEILE,
			new Recipe(1, new Ingredient(15, GRANITZIEGEL), new Ingredient(10, ESCHENBRETTER), new Ingredient(38, EDELMOERTEL))),
	KALK_BODENPLATTE("Kalk-Bodenplatte", 2200, BAUTEILE, new Recipe(1, new Ingredient(12, KALKZIEGEL), new Ingredient(9, MOERTEL))),
	KALK_MAUERSTUECK("Kalk-Mauerstück", 2600, BAUTEILE,
			new Recipe(1, new Ingredient(8, KALKZIEGEL), new Ingredient(6, BUCHENBRETTER), new Ingredient(11, MOERTEL))),
	MARMOR_BODENPLATTE("Marmor-Bodenplatte", 35200, BAUTEILE, new Recipe(1, new Ingredient(32, MARMORZIEGEL), new Ingredient(65, EDELMOERTEL))),
	MARMOR_MAUERSTUECK("Marmor-Mauerstück", 41600, BAUTEILE,
			new Recipe(1, new Ingredient(25, MARMORZIEGEL), new Ingredient(12, EIBENBRETTER), new Ingredient(75, EDELMOERTEL))),
	SAND_BODENPLATTE("Sand-Bodenplatte", 4400, BAUTEILE, new Recipe(1, new Ingredient(12, SANDZIEGEL), new Ingredient(18, MOERTEL))),
	SAND_MAUERSTUECK("Sand-Mauerstück", 5200, BAUTEILE,
			new Recipe(1, new Ingredient(8, SANDZIEGEL), new Ingredient(6, BIRKENBRETTER), new Ingredient(22, MOERTEL))),
	SCHIEFER_BODENPLATTE("Schiefer-Bodenplatte", 8800, BAUTEILE, new Recipe(1, new Ingredient(16, SCHIEFERZIEGEL), new Ingredient(16, EDELMOERTEL))),
	SCHIEFER_MAUERSTUECK("Schiefer-Mauerstück", 10400, BAUTEILE,
			new Recipe(1, new Ingredient(12, SCHIEFERZIEGEL), new Ingredient(7, EICHENBRETTER), new Ingredient(19, EDELMOERTEL))),
	JAGDBOGEN("Jagdbogen", 3000, BÖGEN, new Recipe(1, new Ingredient(16, BUCHENBRETTER), new Ingredient(12, BOGENSALBE))),
	KLINGENBOGEN("Klingenbogen", 37600, BÖGEN,
			new Recipe(1, new Ingredient(34, EIBENBRETTER), new Ingredient(4, BOGENSALBE), new Ingredient(8, ELBENHAAR), new Ingredient(21, GRIFFBAND))),
	KOMPOSITBOGEN("Kompositbogen", 4000, BÖGEN, new Recipe(1, new Ingredient(11, BIRKENBRETTER), new Ingredient(16, BOGENSALBE))),
	KRIEGSBOGEN("Kriegsbogen", 12300, BÖGEN, new Recipe(1, new Ingredient(22, EICHENBRETTER), new Ingredient(10, BOGENSALBE), new Ingredient(16, ELBENHAAR))),
	KURZBOGEN("Kurzbogen", 2000, BÖGEN, new Recipe(1, new Ingredient(11, BUCHENBRETTER), new Ingredient(8, BOGENSALBE))),
	LANGBOGEN("Langbogen", 6100, BÖGEN, new Recipe(1, new Ingredient(16, BIRKENBRETTER), new Ingredient(25, BOGENSALBE))),
	PRUNKBOGEN("Prunkbogen", 57300, BÖGEN,
			new Recipe(1, new Ingredient(52, EIBENBRETTER), new Ingredient(6, BOGENSALBE), new Ingredient(12, ELBENHAAR), new Ingredient(32, GRIFFBAND))),
	RUNENBOGEN("Runenbogen", 24800, BÖGEN, new Recipe(1, new Ingredient(30, ESCHENBRETTER), new Ingredient(14, BOGENSALBE), new Ingredient(35, ELBENHAAR))),
	SPINNENBOGEN("Spinnenbogen", 8100, BÖGEN, new Recipe(1, new Ingredient(15, EICHENBRETTER), new Ingredient(8, BOGENSALBE), new Ingredient(10, ELBENHAAR))),
	ZEDERNBOGEN("Zedernbogen", 16300, BÖGEN, new Recipe(1, new Ingredient(20, ESCHENBRETTER), new Ingredient(12, BOGENSALBE), new Ingredient(22, ELBENHAAR))),
	ASSASSINENKLINGE("Assassinenklinge", 14900, DOLCHE,
			new Recipe(1, new Ingredient(18, ADAMANTBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(22, SCHLEIFSTEIN))),
	DOLCH("Dolch", 1800, DOLCHE, new Recipe(1, new Ingredient(10, KUPFERBARREN), new Ingredient(7, SCHMIEDEOEL))),
	ENTERMESSER("Entermesser", 4900, DOLCHE, new Recipe(1, new Ingredient(9, SORANDILBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(6, SCHLEIFSTEIN))),
	MESSER("Messer", 1200, DOLCHE, new Recipe(1, new Ingredient(7, KUPFERBARREN), new Ingredient(5, SCHMIEDEOEL))),
	NEBELDOLCH("Nebeldolch", 34400, DOLCHE,
			new Recipe(1, new Ingredient(32, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(14, SCHLEIFSTEIN), new Ingredient(16, GRIFFBAND))),
	OCHSENZUNGE("Ochsenzunge", 3700, DOLCHE, new Recipe(1, new Ingredient(10, EISENBARREN), new Ingredient(15, SCHMIEDEOEL))),
	SCHLANGENDOLCH("Schlangendolch", 9800, DOLCHE,
			new Recipe(1, new Ingredient(12, ADAMANTBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(14, SCHLEIFSTEIN))),
	SPITZDOLCH("Spitzdolch", 22600, DOLCHE,
			new Recipe(1, new Ingredient(21, MITHRILBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(10, SCHLEIFSTEIN), new Ingredient(10, GRIFFBAND))),
	STILETT("Stilett", 2400, DOLCHE, new Recipe(1, new Ingredient(7, EISENBARREN), new Ingredient(10, SCHMIEDEOEL))),
	STOSSDOLCH("Stoßdolch", 7400, DOLCHE, new Recipe(1, new Ingredient(14, SORANDILBARREN), new Ingredient(3, SCHMIEDEOEL), new Ingredient(11, SCHLEIFSTEIN))),
	ERDE_EIBENLANZE("Erde-EIbenlanze", 37600, ERDSTÄBE,
			new Recipe(1, new Ingredient(34, EIBENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(10, PHASENKRAUT), new Ingredient(20, ERDENBLUT))),
	ERDE_ESCHENSTAB("Erde-Eschenstab", 24800, ERDSTÄBE,
			new Recipe(1, new Ingredient(30, ESCHENBRETTER), new Ingredient(8, MAGIESPLITTER), new Ingredient(38, PHASENKRAUT))),
	ERDE_KRUMMSTAB("Erde-Krummstab", 3000, ERDSTÄBE, new Recipe(1, new Ingredient(16, BUCHENBRETTER), new Ingredient(16, MAGIESPLITTER))),
	ERDE_LANGHOLZ("Erde-Langholz", 4000, ERDSTÄBE, new Recipe(1, new Ingredient(11, BIRKENBRETTER), new Ingredient(22, MAGIESPLITTER))),
	ERDE_LICHTSTAB("Erde-Lichtstab", 8100, ERDSTÄBE,
			new Recipe(1, new Ingredient(15, EICHENBRETTER), new Ingredient(5, MAGIESPLITTER), new Ingredient(12, PHASENKRAUT))),
	ERDE_RUNENSTAB("Erde-Runenstab", 6100, ERDSTÄBE, new Recipe(1, new Ingredient(17, BIRKENBRETTER), new Ingredient(34, MAGIESPLITTER))),
	ERDE_RUTE("Erde-Rute", 12300, ERDSTÄBE,
			new Recipe(1, new Ingredient(22, EICHENBRETTER), new Ingredient(5, MAGIESPLITTER), new Ingredient(19, PHASENKRAUT))),
	ERDE_SPIRALSTAB("Erde-Spiralstab", 16300, ERDSTÄBE,
			new Recipe(1, new Ingredient(20, ESCHENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(25, PHASENKRAUT))),
	ERDE_STECKEN("Erde-Stecken", 2000, ERDSTÄBE, new Recipe(1, new Ingredient(11, BUCHENBRETTER), new Ingredient(11, MAGIESPLITTER))),
	ERDE_WAECHTERSTAB("Erde-Wächterstab", 57300, ERDSTÄBE,
			new Recipe(1, new Ingredient(52, EIBENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(12, PHASENKRAUT), new Ingredient(32, ERDENBLUT))),
	FEUER_EIBENLANZE("Feuer-Eibenlanze", 37600, FEUERSTÄBE,
			new Recipe(1, new Ingredient(34, EIBENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(10, PHASENKRAUT), new Ingredient(20, ERDENBLUT))),
	FEUER_ESCHENSTAB("Feuer-Eschenstab", 24800, FEUERSTÄBE,
			new Recipe(1, new Ingredient(30, ESCHENBRETTER), new Ingredient(8, MAGIESPLITTER), new Ingredient(38, PHASENKRAUT))),
	FEUER_KRUMMSTAB("Feuer-Krummstab", 3000, FEUERSTÄBE, new Recipe(1, new Ingredient(16, BUCHENBRETTER), new Ingredient(16, MAGIESPLITTER))),
	FEUER_LANGHOLZ("Feuer-Langholz", 4000, FEUERSTÄBE, new Recipe(1, new Ingredient(11, BIRKENBRETTER), new Ingredient(22, MAGIESPLITTER))),
	FEUER_LICHTSTAB("Feuer-Lichtstab", 8100, FEUERSTÄBE,
			new Recipe(1, new Ingredient(15, EICHENBRETTER), new Ingredient(5, MAGIESPLITTER), new Ingredient(12, PHASENKRAUT))),
	FEUER_RUNENSTAB("Feuer-Runenstab", 6100, FEUERSTÄBE, new Recipe(1, new Ingredient(17, BIRKENBRETTER), new Ingredient(34, MAGIESPLITTER))),
	FEUER_RUTE("Feuer-Rute", 12300, FEUERSTÄBE,
			new Recipe(1, new Ingredient(22, EICHENBRETTER), new Ingredient(5, MAGIESPLITTER), new Ingredient(19, PHASENKRAUT))),
	FEUER_SPIRALSTAB("Feuer-Spiralstab", 16300, FEUERSTÄBE,
			new Recipe(1, new Ingredient(20, ESCHENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(25, PHASENKRAUT))),
	FEUER_STECKEN("Feuer-Stecken", 2000, FEUERSTÄBE, new Recipe(1, new Ingredient(11, BUCHENBRETTER), new Ingredient(11, MAGIESPLITTER))),
	FEUER_WAECHTERSTAB("Feuer-Wächterstab", 57300, FEUERSTÄBE,
			new Recipe(1, new Ingredient(52, EIBENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(12, PHASENKRAUT), new Ingredient(32, ERDENBLUT))),
	FLEGEL("Flegel", 3700, KEULEN, new Recipe(1, new Ingredient(10, EISENBARREN), new Ingredient(15, SCHMIEDEOEL))),
	HAMMER("Hammer", 1800, KEULEN, new Recipe(1, new Ingredient(10, KUPFERBARREN), new Ingredient(7, SCHMIEDEOEL))),
	KNUEPPEL("Knüppel", 1200, KEULEN, new Recipe(1, new Ingredient(7, KUPFERBARREN), new Ingredient(5, SCHMIEDEOEL))),
	KRIEGSKNUEPPEL("Kriegsknüppel", 14900, KEULEN,
			new Recipe(1, new Ingredient(18, ADAMANTBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(22, SCHLEIFSTEIN))),
	KRIEGSKOLBEN("Kriegskolben", 7400, KEULEN,
			new Recipe(1, new Ingredient(14, SORANDILBARREN), new Ingredient(3, SCHMIEDEOEL), new Ingredient(11, SCHLEIFSTEIN))),
	KRIEGSZEPTER("Kriegszepter", 22600, KEULEN,
			new Recipe(1, new Ingredient(21, MITHRILBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(10, SCHLEIFSTEIN), new Ingredient(10, GRIFFBAND))),
	MORGENSTERN("Morgenstern", 4900, KEULEN, new Recipe(1, new Ingredient(9, SORANDILBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(6, SCHLEIFSTEIN))),
	OGERHERDE("Ogerherde", 9800, KEULEN, new Recipe(1, new Ingredient(12, ADAMANTBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(14, SCHLEIFSTEIN))),
	STREITKOLBEN("Streitkolben", 2400, KEULEN, new Recipe(1, new Ingredient(7, EISENBARREN), new Ingredient(10, SCHMIEDEOEL))),
	ZACKENSTERN("Zackenstern", 34400, KEULEN,
			new Recipe(1, new Ingredient(32, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(14, SCHLEIFSTEIN), new Ingredient(16, GRIFFBAND))),
	DONNERHAMMER_2H("Donnerhammer [2H]", 57300, KEULEN_2H,
			new Recipe(1, new Ingredient(52, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(8, SCHLEIFSTEIN), new Ingredient(34, GRIFFBAND))),
	EISENKEULE_2H("Eisenkeule [2H]", 7000, KEULEN_2H, new Recipe(1, new Ingredient(19, EISENBARREN), new Ingredient(29, SCHMIEDEOEL))),
	KNOCHENBRECHER_2H("Knochenbrecher [2H]", 18700, KEULEN_2H,
			new Recipe(1, new Ingredient(23, ADAMANTBARREN), new Ingredient(8, SCHMIEDEOEL), new Ingredient(28, SCHLEIFSTEIN))),
	KRIEGSHAMMER_2H("Kriegshammer [2H]", 14200, KEULEN_2H,
			new Recipe(1, new Ingredient(26, SORANDILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(21, SCHLEIFSTEIN))),
	KRIEGSKEULE_2H("Kriegskeule [2H]", 28500, KEULEN_2H,
			new Recipe(1, new Ingredient(35, ADAMANTBARREN), new Ingredient(16, SCHMIEDEOEL), new Ingredient(40, SCHLEIFSTEIN))),
	STABZEPTER_2H("Stabzepter [2H]", 37600, KEULEN_2H,
			new Recipe(1, new Ingredient(34, MITHRILBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(10, SCHLEIFSTEIN), new Ingredient(20, GRIFFBAND))),
	STACHELKEULE_2H("Stachelkeule [2H]", 9300, KEULEN_2H,
			new Recipe(1, new Ingredient(17, SORANDILBARREN), new Ingredient(3, SCHMIEDEOEL), new Ingredient(14, SCHLEIFSTEIN))),
	VORSCHLAGHAMMER_2H("Vorschlaghammer [2H]", 4600, KEULEN_2H, new Recipe(1, new Ingredient(13, EISENBARREN), new Ingredient(19, SCHMIEDEOEL))),
	ACHAT_LEDERBEINLINGE("Achat-Lederbeinlinge", 2200, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(10, LEDER), new Ingredient(14, LEDERFETT), new Ingredient(5, ACHAT))),
	ACHAT_LEDERSTULPEN("Achat-Lederstulpen", 1800, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(7, LEDER), new Ingredient(10, LEDERFETT), new Ingredient(5, ACHAT))),
	DRACHENLEDER_BEINLINGE("Drachenleder-Beinlinge", 28600, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(26, DRACHENLEDER), new Ingredient(8, LEDERFETT), new Ingredient(6, LEDERNIETEN), new Ingredient(15, BESCHLAEGE))),
	DRACHENLEDER_HANDSCHUHE("Drachenleder-Handschuhe", 14100, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(13, DRACHENLEDER), new Ingredient(6, LEDERFETT), new Ingredient(6, LEDERNIETEN), new Ingredient(6, BESCHLAEGE))),
	DRACHENLEDER_HARNISCH("Drachenleder-Harnisch", 37300, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(34, DRACHENLEDER), new Ingredient(15, LEDERFETT), new Ingredient(10, LEDERNIETEN), new Ingredient(18, BESCHLAEGE))),
	DRACHENLEDER_HAUBE("Drachenleder-Haube", 16400, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(15, DRACHENLEDER), new Ingredient(8, LEDERFETT), new Ingredient(9, LEDERNIETEN), new Ingredient(6, BESCHLAEGE))),
	DRACHENLEDER_HELM("Drachenleder-Helm", 24900, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(22, DRACHENLEDER), new Ingredient(8, LEDERFETT), new Ingredient(8, LEDERNIETEN), new Ingredient(12, BESCHLAEGE))),
	DRACHENLEDER_HOSE("Drachenleder-Hose", 18800, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(17, DRACHENLEDER), new Ingredient(6, LEDERFETT), new Ingredient(6, LEDERNIETEN), new Ingredient(9, BESCHLAEGE))),
	DRACHENLEDER_SCHUHE("Drachenleder-Schuhe", 14100, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(13, DRACHENLEDER), new Ingredient(6, LEDERFETT), new Ingredient(6, LEDERNIETEN), new Ingredient(6, BESCHLAEGE))),
	DRACHENLEDER_STIEFEL("Drachenleder-Stiefel", 21500, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(20, DRACHENLEDER), new Ingredient(6, LEDERFETT), new Ingredient(8, LEDERNIETEN), new Ingredient(10, BESCHLAEGE))),
	DRACHENLEDER_STULPEN("Drachenleder-Stulpen", 21500, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(20, DRACHENLEDER), new Ingredient(6, LEDERFETT), new Ingredient(8, LEDERNIETEN), new Ingredient(10, BESCHLAEGE))),
	DRACHENLEDER_WAPPENROCK("Drachenleder-Wappenrock", 24500, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(22, DRACHENLEDER), new Ingredient(14, LEDERFETT), new Ingredient(12, LEDERNIETEN), new Ingredient(9, BESCHLAEGE))),
	HARTLEDER_BEINLINGE("Hartleder-Beinlinge", 7100, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(13, HARTLEDER), new Ingredient(12, LEDERFETT), new Ingredient(7, LEDERNIETEN))),
	HARTLEDER_HANDSCHUHE("Hartleder-Handschuhe", 3500, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(6, HARTLEDER), new Ingredient(7, LEDERFETT), new Ingredient(3, LEDERNIETEN))),
	HARTLEDER_HARNISCH("Hartleder-Harnisch", 9200, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(17, HARTLEDER), new Ingredient(13, LEDERFETT), new Ingredient(10, LEDERNIETEN))),
	HARTLEDER_HAUBE("Hartleder-Haube", 4000, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(7, HARTLEDER), new Ingredient(9, LEDERFETT), new Ingredient(3, LEDERNIETEN))),
	HARTLEDER_HELM("Hartleder-Helm", 6200, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(11, HARTLEDER), new Ingredient(8, LEDERFETT), new Ingredient(7, LEDERNIETEN))),
	HARTLEDER_HOSE("Hartleder-Hose", 4700, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(8, HARTLEDER), new Ingredient(12, LEDERFETT), new Ingredient(3, LEDERNIETEN))),
	HARTLEDER_SCHUHE("Hartleder-Schuhe", 3500, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(6, HARTLEDER), new Ingredient(7, LEDERFETT), new Ingredient(3, LEDERNIETEN))),
	HARTLEDER_STIEFEL("Hartleder-Stiefel", 5300, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(10, HARTLEDER), new Ingredient(12, LEDERFETT), new Ingredient(4, LEDERNIETEN))),
	HARTLEDER_STULPEN("Hartleder-Stulpen", 5300, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(10, HARTLEDER), new Ingredient(12, LEDERFETT), new Ingredient(4, LEDERNIETEN))),
	HARTLEDER_WAPPENROCK("Hartleder-Wappenrock", 6100, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(11, HARTLEDER), new Ingredient(10, LEDERFETT), new Ingredient(6, LEDERNIETEN))),
	LEDER_BEINLINGE("Leder-Beinlinge", 3500, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(10, LEDER), new Ingredient(14, LEDERFETT))),
	LEDER_HANDSCHUHE("Leder-Handschuhe", 1700, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(5, LEDER), new Ingredient(7, LEDERFETT))),
	LEDER_HARNISCH("Leder-Harnisch", 4600, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(12, LEDER), new Ingredient(18, LEDERFETT))),
	LEDER_HAUBE("Leder-Haube", 2000, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(6, LEDER), new Ingredient(8, LEDERFETT))),
	LEDER_HELM("Leder-Helm", 3100, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(8, LEDER), new Ingredient(12, LEDERFETT))),
	LEDER_HOSE("Leder-Hose", 2300, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(6, LEDER), new Ingredient(9, LEDERFETT))),
	LEDER_SCHUHE("Leder-Schuhe", 1700, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(5, LEDER), new Ingredient(7, LEDERFETT))),
	LEDER_STIEFEL("Leder-Stiefel", 2600, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(7, LEDER), new Ingredient(10, LEDERFETT))),
	LEDER_STULPEN("Leder-Stulpen", 2600, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(7, LEDER), new Ingredient(10, LEDERFETT))),
	LEDER_WAPPENROCK("Leder-Wappenrock", 3000, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(8, LEDER), new Ingredient(12, LEDERFETT))),
	RIESENLEDER_BEINLINGE("Riesenleder-Beinlinge", 14200, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(17, RIESENLEDER), new Ingredient(14, LEDERFETT), new Ingredient(18, LEDERNIETEN))),
	RIESENLEDER_HANDSCHUHE("Riesenleder-Handschuhe", 7000, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(8, RIESENLEDER), new Ingredient(9, LEDERFETT), new Ingredient(8, LEDERNIETEN))),
	RIESENLEDER_HARNISCH("Riesenleder-Harnisch", 18600, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(23, RIESENLEDER), new Ingredient(14, LEDERFETT), new Ingredient(25, LEDERNIETEN))),
	RIESENLEDER_HAUBE("Riesenleder-Haube", 8100, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(10, RIESENLEDER), new Ingredient(8, LEDERFETT), new Ingredient(10, LEDERNIETEN))),
	RIESENLEDER_HELM("Riesenleder-Helm", 12400, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(15, RIESENLEDER), new Ingredient(14, LEDERFETT), new Ingredient(15, LEDERNIETEN))),
	RIESENLEDER_HOSE("Riesenleder-Hose", 9400, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(11, RIESENLEDER), new Ingredient(9, LEDERFETT), new Ingredient(12, LEDERNIETEN))),
	RIESENLEDER_SCHUHE("Riesenleder-Schuhe", 7000, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(8, RIESENLEDER), new Ingredient(9, LEDERFETT), new Ingredient(8, LEDERNIETEN))),
	RIESENLEDER_STIEFEL("Riesenleder-Stiefel", 10700, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(13, RIESENLEDER), new Ingredient(14, LEDERFETT), new Ingredient(12, LEDERNIETEN))),
	RIESENLEDER_STULPEN("Riesenleder-Stulpen", 10700, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(13, RIESENLEDER), new Ingredient(14, LEDERFETT), new Ingredient(12, LEDERNIETEN))),
	RIESENLEDER_WAPPENROCK("Riesenleder-Wappenrock", 12200, LEICHTE_RÜSTUNG_LEDER,
			new Recipe(1, new Ingredient(15, RIESENLEDER), new Ingredient(10, LEDERFETT), new Ingredient(16, LEDERNIETEN))),
	WEICHLEDER_BEINLINGE("Weichleder-Beinlinge", 1700, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(10, WEICHLEDER), new Ingredient(7, LEDERFETT))),
	WEICHLEDER_HANDSCHUHE("Weichleder-Handschuhe", 900, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(5, WEICHLEDER), new Ingredient(4, LEDERFETT))),
	WEICHLEDER_HARNISCH("Weichleder-Harnisch", 2300, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(12, WEICHLEDER), new Ingredient(9, LEDERFETT))),
	WEICHLEDER_HAUBE("Weichleder-Haube", 1000, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(6, WEICHLEDER), new Ingredient(4, LEDERFETT))),
	WEICHLEDER_HELM("Weichleder-Helm", 1500, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(8, WEICHLEDER), new Ingredient(6, LEDERFETT))),
	WEICHLEDER_HOSE("Weichleder-Hose", 1200, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(7, WEICHLEDER), new Ingredient(5, LEDERFETT))),
	WEICHLEDER_SCHUHE("Weichleder-Schuhe", 900, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(5, WEICHLEDER), new Ingredient(4, LEDERFETT))),
	WEICHLEDER_STIEFEL("Weichleder-Stiefel", 1300, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(7, WEICHLEDER), new Ingredient(5, LEDERFETT))),
	WEICHLEDER_STULPEN("Weichleder-Stulpen", 1300, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(7, WEICHLEDER), new Ingredient(5, LEDERFETT))),
	WEICHLEDER_WAPPENROCK("Weichleder-Wappenrock", 1500, LEICHTE_RÜSTUNG_LEDER, new Recipe(1, new Ingredient(8, WEICHLEDER), new Ingredient(6, LEDERFETT))),
	BAUMWOLL_BEINLINGE("Baumwoll-Beinlinge", 7100, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(13, BAUMWOLLTUCH), new Ingredient(12, NAEHGARN), new Ingredient(7, SCHUTZPOLSTER))),
	BAUMWOLL_HANDSCHUHE("Baumwoll-Handschuhe", 3500, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(6, BAUMWOLLTUCH), new Ingredient(7, NAEHGARN), new Ingredient(3, SCHUTZPOLSTER))),
	BAUMWOLL_HAUBE("Baumwoll-Haube", 4000, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(7, BAUMWOLLTUCH), new Ingredient(9, NAEHGARN), new Ingredient(3, SCHUTZPOLSTER))),
	BAUMWOLL_HOSE("Baumwoll-Hose", 4700, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(8, BAUMWOLLTUCH), new Ingredient(12, NAEHGARN), new Ingredient(3, SCHUTZPOLSTER))),
	BAUMWOLL_ROBE("Baumwoll-Robe", 6100, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(11, BAUMWOLLTUCH), new Ingredient(10, NAEHGARN), new Ingredient(6, SCHUTZPOLSTER))),
	BAUMWOLL_SCHUHE("Baumwoll-Schuhe", 3500, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(6, BAUMWOLLTUCH), new Ingredient(7, NAEHGARN), new Ingredient(3, SCHUTZPOLSTER))),
	BAUMWOLL_SPITZHUT("Baumwoll-Spitzhut", 6200, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(11, BAUMWOLLTUCH), new Ingredient(8, NAEHGARN), new Ingredient(7, SCHUTZPOLSTER))),
	BAUMWOLL_STIEFEL("Baumwoll-Stiefel", 5300, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(10, BAUMWOLLTUCH), new Ingredient(12, NAEHGARN), new Ingredient(4, SCHUTZPOLSTER))),
	BAUMWOLL_STULPEN("Baumwoll-Stulpen", 5300, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(10, BAUMWOLLTUCH), new Ingredient(12, NAEHGARN), new Ingredient(4, SCHUTZPOLSTER))),
	BAUMWOLL_TUNIKA("Baumwoll-Tunika", 9200, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(17, BAUMWOLLTUCH), new Ingredient(13, NAEHGARN), new Ingredient(10, SCHUTZPOLSTER))),
	LEINEN_BEINLINGE("Leinen-Beinlinge", 1700, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(10, LEINENTUCH), new Ingredient(7, NAEHGARN))),
	LEINEN_HANDSCHUHE("Leinen-Handschuhe", 900, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(5, LEINENTUCH), new Ingredient(4, NAEHGARN))),
	LEINEN_HAUBE("Leinen-Haube", 1000, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(6, LEINENTUCH), new Ingredient(4, NAEHGARN))),
	LEINEN_HOSE("Leinen-Hose", 1200, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(7, LEINENTUCH), new Ingredient(5, NAEHGARN))),
	LEINEN_ROBE("Leinen-Robe", 1500, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(8, LEINENTUCH), new Ingredient(6, NAEHGARN))),
	LEINEN_SCHUHE("Leinen-Schuhe", 900, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(5, LEINENTUCH), new Ingredient(4, NAEHGARN))),
	LEINEN_SPITZHUT("Leinen-Spitzhut", 1500, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(8, LEINENTUCH), new Ingredient(6, NAEHGARN))),
	LEINEN_STIEFEL("Leinen-Stiefel", 1300, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(7, LEINENTUCH), new Ingredient(5, NAEHGARN))),
	LEINEN_STULPEN("Leinen-Stulpen", 1300, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(7, LEINENTUCH), new Ingredient(5, NAEHGARN))),
	LEINEN_TUNIKA("Leinen-Tunika", 2300, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(12, LEINENTUCH), new Ingredient(9, NAEHGARN))),
	SEIDEN_BEINLINGE("Seiden-Beinlinge", 14200, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(17, SEIDENTUCH), new Ingredient(14, NAEHGARN), new Ingredient(18, SCHUTZPOLSTER))),
	SEIDEN_HANDSCHUHE("Seiden-Handschuhe", 7000, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(8, SEIDENTUCH), new Ingredient(9, NAEHGARN), new Ingredient(8, SCHUTZPOLSTER))),
	SEIDEN_HAUBE("Seiden-Haube", 8100, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(10, SEIDENTUCH), new Ingredient(8, NAEHGARN), new Ingredient(10, SCHUTZPOLSTER))),
	SEIDEN_HOSE("Seiden-Hose", 9400, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(11, SEIDENTUCH), new Ingredient(9, NAEHGARN), new Ingredient(12, SCHUTZPOLSTER))),
	SEIDEN_ROBE("Seiden-Robe", 12200, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(15, SEIDENTUCH), new Ingredient(10, NAEHGARN), new Ingredient(16, SCHUTZPOLSTER))),
	SEIDEN_SCHUHE("Seiden-Schuhe", 7000, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(8, SEIDENTUCH), new Ingredient(9, NAEHGARN), new Ingredient(8, SCHUTZPOLSTER))),
	SEIDEN_SPITZHUT("Seiden-Spitzhut", 12400, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(15, SEIDENTUCH), new Ingredient(14, NAEHGARN), new Ingredient(15, SCHUTZPOLSTER))),
	SEIDEN_STIEFEL("Seiden-Stiefel", 10700, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(13, SEIDENTUCH), new Ingredient(14, NAEHGARN), new Ingredient(12, SCHUTZPOLSTER))),
	SEIDEN_STULPEN("Seiden-Stulpen", 10700, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(13, SEIDENTUCH), new Ingredient(14, NAEHGARN), new Ingredient(12, SCHUTZPOLSTER))),
	SEIDEN_TUNIKA("Seiden-Tunika", 18600, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(23, SEIDENTUCH), new Ingredient(14, NAEHGARN), new Ingredient(25, SCHUTZPOLSTER))),
	WOLL_BEINLINGE("Woll-Beinlinge", 3500, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(10, WOLLTUCH), new Ingredient(14, NAEHGARN))),
	WOLL_HANDSCHUHE("Woll-Handschuhe", 1700, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(5, WOLLTUCH), new Ingredient(7, NAEHGARN))),
	WOLL_HAUBE("Woll-Haube", 2000, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(6, WOLLTUCH), new Ingredient(8, NAEHGARN))),
	WOLL_HOSE("Woll-Hose", 2300, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(6, WOLLTUCH), new Ingredient(9, NAEHGARN))),
	WOLL_ROBE("Woll-Robe", 3000, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(8, WOLLTUCH), new Ingredient(12, NAEHGARN))),
	WOLL_SCHUHE("Woll-Schuhe", 1700, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(5, WOLLTUCH), new Ingredient(7, NAEHGARN))),
	WOLL_SPITZHUT("Woll-Spitzhut", 3100, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(8, WOLLTUCH), new Ingredient(12, NAEHGARN))),
	WOLL_STIEFEL("Woll-Stiefel", 2600, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(7, WOLLTUCH), new Ingredient(10, NAEHGARN))),
	WOLL_STULPEN("Woll-Stulpen", 2600, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(7, WOLLTUCH), new Ingredient(10, NAEHGARN))),
	WOLL_TUNIKA("Woll-Tunika", 4600, LEICHTE_RÜSTUNG_STOFF, new Recipe(1, new Ingredient(12, WOLLTUCH), new Ingredient(18, NAEHGARN))),
	AETHER_BEINLINGE("Äther-Beinlinge", 28600, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(26, AETHERTUCH), new Ingredient(8, NAEHGARN), new Ingredient(6, SCHUTZPOLSTER), new Ingredient(15, VULKANDRAHT))),
	AETHER_HANDSCHUHE("Äther-Handschuhe", 14100, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(13, AETHERTUCH), new Ingredient(6, NAEHGARN), new Ingredient(6, SCHUTZPOLSTER), new Ingredient(6, VULKANDRAHT))),
	AETHER_HAUBE("Äther-Haube", 16400, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(15, AETHERTUCH), new Ingredient(8, NAEHGARN), new Ingredient(9, SCHUTZPOLSTER), new Ingredient(6, VULKANDRAHT))),
	AETHER_HOSE("Äther-Hose", 18800, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(17, AETHERTUCH), new Ingredient(6, NAEHGARN), new Ingredient(6, SCHUTZPOLSTER), new Ingredient(9, VULKANDRAHT))),
	AETHER_ROBE("Äther-Robe", 24500, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(22, AETHERTUCH), new Ingredient(14, NAEHGARN), new Ingredient(12, SCHUTZPOLSTER), new Ingredient(9, VULKANDRAHT))),
	AETHER_SCHUHE("Äther-Schuhe", 14100, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(13, AETHERTUCH), new Ingredient(6, NAEHGARN), new Ingredient(6, SCHUTZPOLSTER), new Ingredient(6, VULKANDRAHT))),
	AETHER_SPITZHUT("Äther-Spitzhut", 24900, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(22, AETHERTUCH), new Ingredient(8, NAEHGARN), new Ingredient(8, SCHUTZPOLSTER), new Ingredient(12, VULKANDRAHT))),
	AETHER_STIEFEL("Äther-Stiefel", 21500, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(20, AETHERTUCH), new Ingredient(6, NAEHGARN), new Ingredient(8, SCHUTZPOLSTER), new Ingredient(10, VULKANDRAHT))),
	AETHER_STULPEN("Äther-Stulpen", 21500, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(20, AETHERTUCH), new Ingredient(6, NAEHGARN), new Ingredient(8, SCHUTZPOLSTER), new Ingredient(10, VULKANDRAHT))),
	AETHER_TUNIKA("Äther-Tunika", 37300, LEICHTE_RÜSTUNG_STOFF,
			new Recipe(1, new Ingredient(34, AETHERTUCH), new Ingredient(15, NAEHGARN), new Ingredient(10, SCHUTZPOLSTER), new Ingredient(18, VULKANDRAHT))),
	BESCHUETZER("Beschützer", 6200, LEICHTE_SCHILDE,
			new Recipe(1, new Ingredient(11, HARTLEDER), new Ingredient(8, LEDERFETT), new Ingredient(7, LEDERNIETEN))),
	DORNENSCHILD("Dornenschild", 8100, LEICHTE_SCHILDE,
			new Recipe(1, new Ingredient(10, RIESENLEDER), new Ingredient(8, LEDERFETT), new Ingredient(5, LEDERNIETEN), new Ingredient(2, BESCHLAEGE))),
	LEDERSCHILD("Lederschild", 1000, LEICHTE_SCHILDE, new Recipe(1, new Ingredient(5, WEICHLEDER), new Ingredient(4, LEDERFETT))),
	NEBELSCHILD("Nebelschild", 24900, LEICHTE_SCHILDE,
			new Recipe(1, new Ingredient(23, DRACHENLEDER), new Ingredient(8, LEDERFETT), new Ingredient(8, LEDERNIETEN), new Ingredient(12, BESCHLAEGE))),
	NIETENSCHILD("Nietenschild", 12400, LEICHTE_SCHILDE,
			new Recipe(1, new Ingredient(15, RIESENLEDER), new Ingredient(9, LEDERFETT), new Ingredient(7, LEDERNIETEN), new Ingredient(4, BESCHLAEGE))),
	RUNDSCHILD("Rundschild", 1500, LEICHTE_SCHILDE, new Recipe(1, new Ingredient(8, WEICHLEDER), new Ingredient(6, LEDERFETT))),
	STACHELSCHILD("Stachelschild", 4000, LEICHTE_SCHILDE,
			new Recipe(1, new Ingredient(7, HARTLEDER), new Ingredient(9, LEDERFETT), new Ingredient(3, LEDERNIETEN))),
	TARTSCHE("Tartsche", 2000, LEICHTE_SCHILDE, new Recipe(1, new Ingredient(5, LEDER), new Ingredient(8, LEDERFETT))),
	VERTEIDIGER("Verteidiger", 16400, LEICHTE_SCHILDE,
			new Recipe(1, new Ingredient(15, DRACHENLEDER), new Ingredient(6, LEDERFETT), new Ingredient(5, LEDERNIETEN), new Ingredient(8, BESCHLAEGE))),
	ZIRKELSCHILD("Zirkelschild", 3100, LEICHTE_SCHILDE, new Recipe(1, new Ingredient(8, LEDER), new Ingredient(12, LEDERFETT))),
	LUFT_EIBENLANZE("Luft-Eibenlanze", 37600, LUFTSTÄBE,
			new Recipe(1, new Ingredient(34, EIBENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(10, PHASENKRAUT), new Ingredient(20, ERDENBLUT))),
	LUFT_ESCHENSTAB("Luft-Eschenstab", 24800, LUFTSTÄBE,
			new Recipe(1, new Ingredient(30, ESCHENBRETTER), new Ingredient(8, MAGIESPLITTER), new Ingredient(38, PHASENKRAUT))),
	LUFT_KRUMMSTAB("Luft-Krummstab", 3000, LUFTSTÄBE, new Recipe(1, new Ingredient(16, BUCHENBRETTER), new Ingredient(16, MAGIESPLITTER))),
	LUFT_LANGHOLZ("Luft-Langholz", 4000, LUFTSTÄBE, new Recipe(1, new Ingredient(11, BIRKENBRETTER), new Ingredient(22, MAGIESPLITTER))),
	LUFT_LICHTSTAB("Luft-Lichtstab", 8100, LUFTSTÄBE,
			new Recipe(1, new Ingredient(15, EICHENBRETTER), new Ingredient(5, MAGIESPLITTER), new Ingredient(12, PHASENKRAUT))),
	LUFT_RUNENSTAB("Luft-Runenstab", 6100, LUFTSTÄBE, new Recipe(1, new Ingredient(17, BIRKENBRETTER), new Ingredient(34, MAGIESPLITTER))),
	LUFT_RUTE("Luft-Rute", 12300, LUFTSTÄBE,
			new Recipe(1, new Ingredient(22, EICHENBRETTER), new Ingredient(5, MAGIESPLITTER), new Ingredient(19, PHASENKRAUT))),
	LUFT_SPIRALSTAB("Luft-Spiralstab", 16300, LUFTSTÄBE,
			new Recipe(1, new Ingredient(20, ESCHENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(25, PHASENKRAUT))),
	LUFT_STECKEN("Luft-Stecken", 2000, LUFTSTÄBE, new Recipe(1, new Ingredient(11, BUCHENBRETTER), new Ingredient(11, MAGIESPLITTER))),
	LUFT_WAECHTERSTAB("Luft-Wächterstab", 57300, LUFTSTÄBE,
			new Recipe(1, new Ingredient(52, EIBENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(12, PHASENKRAUT), new Ingredient(32, ERDENBLUT))),
	BOLZEN("Bolzen", 12, MUNITION_ARMBRÜSTE, new Recipe(33, new Ingredient(6, BUCHENHOLZ), new Ingredient(5, FEDERN))),
	DAEMONENDORN("Dämonendorn", 36, MUNITION_ARMBRÜSTE,
			new Recipe(90, new Ingredient(11, ESCHENHOLZ), new Ingredient(10, FEDERN), new Ingredient(5, PFEILHARZ))),
	JAGDBOLZEN("Jagdbolzen", 20, MUNITION_ARMBRÜSTE, new Recipe(40, new Ingredient(6, BIRKENHOLZ), new Ingredient(10, FEDERN))),
	KRIEGSBOLZEN("Kriegsbolzen", 28, MUNITION_ARMBRÜSTE,
			new Recipe(57, new Ingredient(8, EICHENHOLZ), new Ingredient(7, FEDERN), new Ingredient(2, PFEILHARZ))),
	STEINBRECHER("Steinbrecher", 0, MUNITION_ARMBRÜSTE,
			new Recipe(152, new Ingredient(16, EIBENHOLZ), new Ingredient(9, FEDERN), new Ingredient(8, PFEILHARZ), new Ingredient(1, DRACHINSCHNEIDEN))),
	GOETTERSTICH("Götterstich", 9, MUNITION_BÖGEN, new Recipe(360, new Ingredient(11, ESCHENHOLZ), new Ingredient(10, FEDERN), new Ingredient(5, PFEILHARZ))),
	JAGDPFEILE("Jagdpfeile", 4, MUNITION_BÖGEN, new Recipe(163, new Ingredient(6, BIRKENHOLZ), new Ingredient(10, FEDERN))),
	KRIEGSPFEILE("Kriegspfeile", 7, MUNITION_BÖGEN, new Recipe(228, new Ingredient(8, EICHENHOLZ), new Ingredient(7, FEDERN), new Ingredient(2, PFEILHARZ))),
	PANZERBRECHER("Panzerbrecher", 11, MUNITION_BÖGEN,
			new Recipe(610, new Ingredient(16, EIBENHOLZ), new Ingredient(9, FEDERN), new Ingredient(8, PFEILHARZ), new Ingredient(1, DRACHINSCHNEIDEN))),
	PFEILE("Pfeile", 3, MUNITION_BÖGEN, new Recipe(135, new Ingredient(6, BUCHENHOLZ), new Ingredient(5, FEDERN))),
	MAGIEESSENZ("Magieessenz", 4, MUNITION_MAGIESTÄBE, new Recipe(100, new Ingredient(6, MAGIESTAUB), new Ingredient(2, MAGIESPLITTER))),
	MONDESSENZ("Mondessenz", 12, MUNITION_MAGIESTÄBE,
			new Recipe(270, new Ingredient(11, MONDSTAUB), new Ingredient(7, MAGIESPLITTER), new Ingredient(3, PHASENKRAUT))),
	SCHATTENESSENZ("Schattenessenz", 9, MUNITION_MAGIESTÄBE,
			new Recipe(180, new Ingredient(8, SCHATTENSTAUB), new Ingredient(5, MAGIESPLITTER), new Ingredient(1, PHASENKRAUT))),
	STERNENESSENZ("Sternenessenz", 15, MUNITION_MAGIESTÄBE,
			new Recipe(450, new Ingredient(16, STERNENSTAUB), new Ingredient(8, MAGIESPLITTER), new Ingredient(5, PHASENKRAUT), new Ingredient(1, ERDENBLUT))),
	TODESESSENZ("Todesessenz", 7, MUNITION_MAGIESTÄBE, new Recipe(115, new Ingredient(6, TODESSTAUB), new Ingredient(4, MAGIESPLITTER))),
	ADAMANT_KETTENBEINLINGE("Adamant-Kettenbeinlinge", 9400, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(11, ADAMANTBARREN), new Ingredient(9, SCHMIEDEOEL), new Ingredient(12, WATTIERUNG))),
	ADAMANT_KETTENHANDSCHUHE("Adamant-Kettenhandschuhe", 7000, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(8, ADAMANTBARREN), new Ingredient(9, SCHMIEDEOEL), new Ingredient(8, WATTIERUNG))),
	ADAMANT_KETTENHAUBE("Adamant-Kettenhaube", 8100, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(10, ADAMANTBARREN), new Ingredient(8, SCHMIEDEOEL), new Ingredient(10, WATTIERUNG))),
	ADAMANT_KETTENHEMD("Adamant-Kettenhemd", 12200, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(15, ADAMANTBARREN), new Ingredient(10, SCHMIEDEOEL), new Ingredient(16, WATTIERUNG))),
	ADAMANT_KETTENSTIEFEL("Adamant-Kettenstiefel", 7000, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(8, ADAMANTBARREN), new Ingredient(9, SCHMIEDEOEL), new Ingredient(8, WATTIERUNG))),
	ADAMANT_PLATTENBEINLINGE("Adamant-Plattenbeinlinge", 14200, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(17, ADAMANTBARREN), new Ingredient(14, SCHMIEDEOEL), new Ingredient(18, WATTIERUNG))),
	ADAMANT_PLATTENHANDSCHUHE("Adamant-Plattenhandschuhe", 10700, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(13, ADAMANTBARREN), new Ingredient(14, SCHMIEDEOEL), new Ingredient(12, WATTIERUNG))),
	ADAMANT_PLATTENHELM("Adamant-Plattenhelm", 12400, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(15, ADAMANTBARREN), new Ingredient(14, SCHMIEDEOEL), new Ingredient(15, WATTIERUNG))),
	ADAMANT_PLATTENPANZER("Adamant-Plattenpanzer", 18600, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(23, ADAMANTBARREN), new Ingredient(14, SCHMIEDEOEL), new Ingredient(25, WATTIERUNG))),
	ADAMANT_PLATTENSTIEFEL("Adamant-Plattenstiefel", 10700, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(13, ADAMANTBARREN), new Ingredient(14, SCHMIEDEOEL), new Ingredient(12, WATTIERUNG))),
	EISEN_KETTENBEINLINGE("Eisen-Kettenbeinlinge", 2300, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(6, EISENBARREN), new Ingredient(9, SCHMIEDEOEL))),
	EISEN_KETTENHANDSCHUHE("Eisen-Kettenhandschuhe", 1700, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(5, EISENBARREN), new Ingredient(7, SCHMIEDEOEL))),
	EISEN_KETTENHAUBE("Eisen-Kettenhaube", 2000, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(6, EISENBARREN), new Ingredient(8, SCHMIEDEOEL))),
	EISEN_KETTENHEMD("Eisen-Kettenhemd", 3000, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(8, EISENBARREN), new Ingredient(12, SCHMIEDEOEL))),
	EISEN_KETTENSTIEFEL("Eisen-Kettenstiefel", 1700, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(5, EISENBARREN), new Ingredient(7, SCHMIEDEOEL))),
	EISEN_PLATTENBEINLINGE("Eisen-Plattenbeinlinge", 3500, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(10, EISENBARREN), new Ingredient(14, SCHMIEDEOEL))),
	EISEN_PLATTENHANDSCHUHE("Eisen-Plattenhandschuhe", 2600, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(7, EISENBARREN), new Ingredient(10, SCHMIEDEOEL))),
	EISEN_PLATTENHELM("Eisen-Plattenhelm", 3100, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(8, EISENBARREN), new Ingredient(12, SCHMIEDEOEL))),
	EISEN_PLATTENPANZER("Eisen-Plattenpanzer", 4600, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(12, EISENBARREN), new Ingredient(18, SCHMIEDEOEL))),
	EISEN_PLATTENSTIEFEL("Eisen-Plattenstiefel", 2600, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(7, EISENBARREN), new Ingredient(10, SCHMIEDEOEL))),
	KUPFER_KETTENBEINLINGE("Kupfer-Kettenbeinlinge", 1200, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(7, KUPFERBARREN), new Ingredient(5, SCHMIEDEOEL))),
	KUPFER_KETTENHANDSCHUHE("Kupfer-Kettenhandschuhe", 900, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(5, KUPFERBARREN), new Ingredient(4, SCHMIEDEOEL))),
	KUPFER_KETTENHAUBE("Kupfer-Kettenhaube", 1000, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(6, KUPFERBARREN), new Ingredient(4, SCHMIEDEOEL))),
	KUPFER_KETTENHEMD("Kupfer-Kettenhemd", 1500, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(8, KUPFERBARREN), new Ingredient(6, SCHMIEDEOEL))),
	KUPFER_KETTENSTIEFEL("Kupfer-Kettenstiefel", 900, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(5, KUPFERBARREN), new Ingredient(4, SCHMIEDEOEL))),
	KUPFER_PLATTENBEINLINGE("Kupfer-Plattenbeinlinge", 1700, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(10, KUPFERBARREN), new Ingredient(7, SCHMIEDEOEL))),
	KUPFER_PLATTENHANDSCHUHE("Kupfer-Plattenhandschuhe", 1300, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(7, KUPFERBARREN), new Ingredient(5, SCHMIEDEOEL))),
	KUPFER_PLATTENHELM("Kupfer-Plattenhelm", 1500, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(8, KUPFERBARREN), new Ingredient(6, SCHMIEDEOEL))),
	KUPFER_PLATTENPANZER("Kupfer-Plattenpanzer", 2300, SCHWERE_RÜSTUNG_METALL, new Recipe(1, new Ingredient(12, KUPFERBARREN), new Ingredient(9, SCHMIEDEOEL))),
	KUPFER_PLATTENSTIEFEL("Kupfer-Plattenstiefel", 1300, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(7, KUPFERBARREN), new Ingredient(5, SCHMIEDEOEL))),
	MITHRIL_KETTENBEINLINGE("Mithril-Kettenbeinlinge", 18800, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(17, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(6, WATTIERUNG), new Ingredient(9, NIETEN))),
	MITHRIL_KETTENHANDSCHUHE("Mithril-Kettenhandschuhe", 14100, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(13, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(6, WATTIERUNG), new Ingredient(6, NIETEN))),
	MITHRIL_KETTENHAUBE("Mithril-Kettenhaube", 16400, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(15, MITHRILBARREN), new Ingredient(8, SCHMIEDEOEL), new Ingredient(9, WATTIERUNG), new Ingredient(6, NIETEN))),
	MITHRIL_KETTENHEMD("Mithril-Kettenhemd", 24500, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(22, MITHRILBARREN), new Ingredient(14, SCHMIEDEOEL), new Ingredient(12, WATTIERUNG), new Ingredient(9, NIETEN))),
	MITHRIL_KETTENSTIEFEL("Mithril-Kettenstiefel", 14100, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(13, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(6, WATTIERUNG), new Ingredient(6, NIETEN))),
	MITHRIL_PLATTENBEINLINGE("Mithril-Plattenbeinlinge", 28600, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(26, MITHRILBARREN), new Ingredient(8, SCHMIEDEOEL), new Ingredient(6, WATTIERUNG), new Ingredient(15, NIETEN))),
	MITHRIL_PLATTENHANDSCHUHE("Mithril-Plattenhandschuhe", 21500, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(20, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(8, WATTIERUNG), new Ingredient(10, NIETEN))),
	MITHRIL_PLATTENHELM("Mithril-Plattenhelm", 24900, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(22, MITHRILBARREN), new Ingredient(8, SCHMIEDEOEL), new Ingredient(8, WATTIERUNG), new Ingredient(12, NIETEN))),
	MITHRIL_PLATTENPANZER("Mithril-Plattenpanzer", 37300, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(34, MITHRILBARREN), new Ingredient(15, SCHMIEDEOEL), new Ingredient(10, WATTIERUNG), new Ingredient(18, NIETEN))),
	MITHRIL_PLATTENSTIEFEL("Mithril-Plattenstiefel", 21500, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(20, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(8, WATTIERUNG), new Ingredient(10, NIETEN))),
	SORANDIL_KETTENBEINLINGE("Sorandil-Kettenbeinlinge", 4700, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(8, SORANDILBARREN), new Ingredient(12, SCHMIEDEOEL), new Ingredient(3, WATTIERUNG))),
	SORANDIL_KETTENHANDSCHUHE("Sorandil-Kettenhandschuhe", 3500, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(6, SORANDILBARREN), new Ingredient(7, SCHMIEDEOEL), new Ingredient(3, WATTIERUNG))),
	SORANDIL_KETTENHAUBE("Sorandil-Kettenhaube", 4000, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(7, SORANDILBARREN), new Ingredient(9, SCHMIEDEOEL), new Ingredient(3, WATTIERUNG))),
	SORANDIL_KETTENHEMD("Sorandil-Kettenhemd", 6100, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(11, SORANDILBARREN), new Ingredient(10, SCHMIEDEOEL), new Ingredient(6, WATTIERUNG))),
	SORANDIL_KETTENSTIEFEL("Sorandil-Kettenstiefel", 3500, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(6, SORANDILBARREN), new Ingredient(7, SCHMIEDEOEL), new Ingredient(3, WATTIERUNG))),
	SORANDIL_PLATTENBEINLINGE("Sorandil-Plattenbeinlinge", 7100, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(13, SORANDILBARREN), new Ingredient(12, SCHMIEDEOEL), new Ingredient(7, WATTIERUNG))),
	SORANDIL_PLATTENHANDSCHUHE("Sorandil-Plattenhandschuhe", 5300, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(10, SORANDILBARREN), new Ingredient(12, SCHMIEDEOEL), new Ingredient(4, WATTIERUNG))),
	SORANDIL_PLATTENHELM("Sorandil-Plattenhelm", 6200, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(11, SORANDILBARREN), new Ingredient(8, SCHMIEDEOEL), new Ingredient(7, WATTIERUNG))),
	SORANDIL_PLATTENPANZER("Sorandil-Plattenpanzer", 9200, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(17, SORANDILBARREN), new Ingredient(13, SCHMIEDEOEL), new Ingredient(10, WATTIERUNG))),
	SORANDIL_PLATTENSTIEFEL("Sorandil-Plattenstiefel", 5300, SCHWERE_RÜSTUNG_METALL,
			new Recipe(1, new Ingredient(10, SORANDILBARREN), new Ingredient(12, SCHMIEDEOEL), new Ingredient(4, WATTIERUNG))),
	DRACHENSCHILD("Drachenschild", 2800, SCHWERER_SCHILDE, new Recipe(1, new Ingredient(8, EISENBARREN), new Ingredient(12, SCHMIEDEOEL))),
	ECKSCHILD("Eckschild", 1400, SCHWERER_SCHILDE, new Recipe(1, new Ingredient(8, KUPFERBARREN), new Ingredient(6, SCHMIEDEOEL))),
	GOTHIKA("Gothika", 4200, SCHWERER_SCHILDE, new Recipe(1, new Ingredient(12, EISENBARREN), new Ingredient(18, SCHMIEDEOEL))),
	KAMPFSCHILD("Kampfschild", 2100, SCHWERER_SCHILDE, new Recipe(1, new Ingredient(12, KUPFERBARREN), new Ingredient(9, SCHMIEDEOEL))),
	MONARCHENSCHILD("Monarchenschild", 34400, SCHWERER_SCHILDE,
			new Recipe(1, new Ingredient(32, MITHRILBARREN), new Ingredient(15, SCHMIEDEOEL), new Ingredient(10, LEDERNIETEN), new Ingredient(16, BESCHLAEGE))),
	PAVESE("Pavese", 5600, SCHWERER_SCHILDE, new Recipe(1, new Ingredient(10, SORANDILBARREN), new Ingredient(8, SCHMIEDEOEL), new Ingredient(6, LEDERNIETEN))),
	PRUNKSCHILD("Prunkschild", 8500, SCHWERER_SCHILDE,
			new Recipe(1, new Ingredient(15, SORANDILBARREN), new Ingredient(10, SCHMIEDEOEL), new Ingredient(10, LEDERNIETEN))),
	TURMSCHILD("Turmschild", 17100, SCHWERER_SCHILDE,
			new Recipe(1, new Ingredient(21, ADAMANTBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(6, LEDERNIETEN), new Ingredient(8, BESCHLAEGE))),
	WALL("Wall", 22600, SCHWERER_SCHILDE,
			new Recipe(1, new Ingredient(21, MITHRILBARREN), new Ingredient(10, SCHMIEDEOEL), new Ingredient(8, LEDERNIETEN), new Ingredient(10, BESCHLAEGE))),
	WAPPENSCHILD("Wappenschild", 11200, SCHWERER_SCHILDE,
			new Recipe(1, new Ingredient(14, ADAMANTBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(4, LEDERNIETEN), new Ingredient(5, BESCHLAEGE))),
	BREITSCHWERT("Breitschwert", 2400, SCHWERTER, new Recipe(1, new Ingredient(7, EISENBARREN), new Ingredient(10, SCHMIEDEOEL))),
	GLADIUS("Gladius", 14900, SCHWERTER, new Recipe(1, new Ingredient(18, ADAMANTBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(22, SCHLEIFSTEIN))),
	KRUMMSCHWERT("Krummschwert", 9800, SCHWERTER,
			new Recipe(1, new Ingredient(12, ADAMANTBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(14, SCHLEIFSTEIN))),
	KRUMMSAEBEL("Krummsäbel", 4900, SCHWERTER,
			new Recipe(1, new Ingredient(9, SORANDILBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(6, SCHLEIFSTEIN))),
	KURZSCHWERT("Kurzschwert", 1200, SCHWERTER, new Recipe(1, new Ingredient(7, KUPFERBARREN), new Ingredient(5, SCHMIEDEOEL))),
	LANGSCHWERT("Langschwert", 7400, SCHWERTER,
			new Recipe(1, new Ingredient(14, SORANDILBARREN), new Ingredient(3, SCHMIEDEOEL), new Ingredient(11, SCHLEIFSTEIN))),
	LILIENKLINGE("Lilienklinge", 34400, SCHWERTER,
			new Recipe(1, new Ingredient(32, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(14, SCHLEIFSTEIN), new Ingredient(16, GRIFFBAND))),
	SCHIMMERKLINGE("Schimmerklinge", 22600, SCHWERTER,
			new Recipe(1, new Ingredient(21, MITHRILBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(10, SCHLEIFSTEIN), new Ingredient(10, GRIFFBAND))),
	SCHWERT("Schwert", 1800, SCHWERTER, new Recipe(1, new Ingredient(10, KUPFERBARREN), new Ingredient(7, SCHMIEDEOEL))),
	SAEBEL("Säbel", 3700, SCHWERTER, new Recipe(1, new Ingredient(10, EISENBARREN), new Ingredient(15, SCHMIEDEOEL))),
	BASTARDSCHWERT_2H("Bastardschwert [2H]", 4600, SCHWERTER_2H, new Recipe(1, new Ingredient(13, EISENBARREN), new Ingredient(19, SCHMIEDEOEL))),
	BIDENHAENDER_2H("Bidenhänder [2H]", 7000, SCHWERTER_2H, new Recipe(1, new Ingredient(19, EISENBARREN), new Ingredient(29, SCHMIEDEOEL))),
	ELBENBANN_2H("Elbenbann [2H]", 28500, SCHWERTER_2H,
			new Recipe(1, new Ingredient(35, ADAMANTBARREN), new Ingredient(16, SCHMIEDEOEL), new Ingredient(40, SCHLEIFSTEIN))),
	ENGELSKLINGE_2H("Engelsklinge [2H]", 57300, SCHWERTER_2H,
			new Recipe(1, new Ingredient(52, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(8, SCHLEIFSTEIN), new Ingredient(34, GRIFFBAND))),
	FLAMBERGE_2H("Flamberge [2H]", 14200, SCHWERTER_2H,
			new Recipe(1, new Ingredient(26, SORANDILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(21, SCHLEIFSTEIN))),
	MONDKLINGE_2H("Mondklinge [2H]", 37600, SCHWERTER_2H,
			new Recipe(1, new Ingredient(34, MITHRILBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(10, SCHLEIFSTEIN), new Ingredient(20, GRIFFBAND))),
	PRUNKSCHWERT_2H("Prunkschwert [2H]", 18700, SCHWERTER_2H,
			new Recipe(1, new Ingredient(23, ADAMANTBARREN), new Ingredient(8, SCHMIEDEOEL), new Ingredient(28, SCHLEIFSTEIN))),
	SCHOTTENSCHWERT_2H("Schottenschwert [2H]", 9300, SCHWERTER_2H,
			new Recipe(1, new Ingredient(17, SORANDILBARREN), new Ingredient(3, SCHMIEDEOEL), new Ingredient(14, SCHLEIFSTEIN))),
	BAUERNSENSE_2H("Bauernsense [2H]", 3000, STANGENWAFFEN_2H, new Recipe(1, new Ingredient(16, KUPFERBARREN), new Ingredient(12, SCHMIEDEOEL))),
	DREIZACK_2H("Dreizack [2H]", 16300, STANGENWAFFEN_2H,
			new Recipe(1, new Ingredient(20, ADAMANTBARREN), new Ingredient(12, SCHMIEDEOEL), new Ingredient(22, SCHLEIFSTEIN))),
	DRESCHER_2H("Drescher [2H]", 37600, STANGENWAFFEN_2H,
			new Recipe(1, new Ingredient(34, MITHRILBARREN), new Ingredient(4, SCHMIEDEOEL), new Ingredient(8, SCHLEIFSTEIN), new Ingredient(21, GRIFFBAND))),
	HELLEBARDE_2H("Hellebarde [2H]", 24800, STANGENWAFFEN_2H,
			new Recipe(1, new Ingredient(30, ADAMANTBARREN), new Ingredient(14, SCHMIEDEOEL), new Ingredient(35, SCHLEIFSTEIN))),
	JAGDSPEER_2H("Jagdspeer [2H]", 4000, STANGENWAFFEN_2H, new Recipe(1, new Ingredient(11, EISENBARREN), new Ingredient(16, SCHMIEDEOEL))),
	KRIEGSPIKE_2H("Kriegspike [2H]", 57300, STANGENWAFFEN_2H,
			new Recipe(1, new Ingredient(52, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(12, SCHLEIFSTEIN), new Ingredient(32, GRIFFBAND))),
	LANZE_2H("Lanze [2H]", 12300, STANGENWAFFEN_2H,
			new Recipe(1, new Ingredient(22, SORANDILBARREN), new Ingredient(10, SCHMIEDEOEL), new Ingredient(16, SCHLEIFSTEIN))),
	PIKE_2H("Pike [2H]", 8100, STANGENWAFFEN_2H,
			new Recipe(1, new Ingredient(15, SORANDILBARREN), new Ingredient(8, SCHMIEDEOEL), new Ingredient(10, SCHLEIFSTEIN))),
	SENSE_2H("Sense [2H]", 6100, STANGENWAFFEN_2H, new Recipe(1, new Ingredient(16, EISENBARREN), new Ingredient(25, SCHMIEDEOEL))),
	SPEER_2H("Speer [2H]", 2000, STANGENWAFFEN_2H, new Recipe(1, new Ingredient(11, KUPFERBARREN), new Ingredient(8, SCHMIEDEOEL))),
	WASSER_EIBENLANZE("Wasser-Eibenlanze", 37600, WASSERSTÄBE,
			new Recipe(1, new Ingredient(34, EIBENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(10, PHASENKRAUT), new Ingredient(20, ERDENBLUT))),
	WASSER_ESCHENSTAB("Wasser-Eschenstab", 24800, WASSERSTÄBE,
			new Recipe(1, new Ingredient(30, ESCHENBRETTER), new Ingredient(8, MAGIESPLITTER), new Ingredient(38, PHASENKRAUT))),
	WASSER_KRUMMSTAB("Wasser-Krummstab", 3000, WASSERSTÄBE, new Recipe(1, new Ingredient(16, BUCHENBRETTER), new Ingredient(16, MAGIESPLITTER))),
	WASSER_LANGHOLZ("Wasser-Langholz", 4000, WASSERSTÄBE, new Recipe(1, new Ingredient(11, BIRKENBRETTER), new Ingredient(22, MAGIESPLITTER))),
	WASSER_LICHTSTAB("Wasser-Lichtstab", 8100, WASSERSTÄBE,
			new Recipe(1, new Ingredient(15, EICHENBRETTER), new Ingredient(5, MAGIESPLITTER), new Ingredient(12, PHASENKRAUT))),
	WASSER_RUNENSTAB("Wasser-Runenstab", 6100, WASSERSTÄBE, new Recipe(1, new Ingredient(17, BIRKENBRETTER), new Ingredient(34, MAGIESPLITTER))),
	WASSER_RUTE("Wasser-Rute", 12300, WASSERSTÄBE,
			new Recipe(1, new Ingredient(22, EICHENBRETTER), new Ingredient(5, MAGIESPLITTER), new Ingredient(19, PHASENKRAUT))),
	WASSER_SPIRALSTAB("Wasser-Spiralstab", 16300, WASSERSTÄBE,
			new Recipe(1, new Ingredient(20, ESCHENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(25, PHASENKRAUT))),
	WASSER_STECKEN("Wasser-Stecken", 2000, WASSERSTÄBE, new Recipe(1, new Ingredient(11, BUCHENBRETTER), new Ingredient(11, MAGIESPLITTER))),
	WASSER_WAECHTERSTAB("Wasser-Wächterstab", 57300, WASSERSTÄBE,
			new Recipe(1, new Ingredient(52, EIBENBRETTER), new Ingredient(6, MAGIESPLITTER), new Ingredient(12, PHASENKRAUT), new Ingredient(32, ERDENBLUT))),
	AXT("Axt", 1200, ÄXTE, new Recipe(1, new Ingredient(7, KUPFERBARREN), new Ingredient(5, SCHMIEDEOEL))),
	BARBARENAXT("Barbarenaxt", 4900, ÄXTE, new Recipe(1, new Ingredient(9, SORANDILBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(6, SCHLEIFSTEIN))),
	BREITAXT("Breitaxt", 3700, ÄXTE, new Recipe(1, new Ingredient(10, EISENBARREN), new Ingredient(15, SCHMIEDEOEL))),
	FRANZISKA("Franziska", 34400, ÄXTE,
			new Recipe(1, new Ingredient(32, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(14, SCHLEIFSTEIN), new Ingredient(16, GRIFFBAND))),
	HOLZFAELLERAXT("Holzfälleraxt", 2400, ÄXTE, new Recipe(1, new Ingredient(7, EISENBARREN), new Ingredient(10, SCHMIEDEOEL))),
	KRIEGSBEIL("Kriegsbeil", 14900, ÄXTE, new Recipe(1, new Ingredient(18, ADAMANTBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(22, SCHLEIFSTEIN))),
	MILITAERPICKE("Militärpicke", 7400, ÄXTE,
			new Recipe(1, new Ingredient(14, SORANDILBARREN), new Ingredient(3, SCHMIEDEOEL), new Ingredient(11, SCHLEIFSTEIN))),
	STREITAXT("Streitaxt", 1800, ÄXTE, new Recipe(1, new Ingredient(10, KUPFERBARREN), new Ingredient(7, SCHMIEDEOEL))),
	TOMAHAWK("Tomahawk", 22600, ÄXTE,
			new Recipe(1, new Ingredient(21, MITHRILBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(10, SCHLEIFSTEIN), new Ingredient(10, GRIFFBAND))),
	ZWILLINGSAXT("Zwillingsaxt", 9800, ÄXTE,
			new Recipe(1, new Ingredient(12, ADAMANTBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(14, SCHLEIFSTEIN))),
	BERSERKERAXT_2H("Berserkeraxt [2H]", 37600, ÄXTE_2H,
			new Recipe(1, new Ingredient(34, MITHRILBARREN), new Ingredient(5, SCHMIEDEOEL), new Ingredient(10, SCHLEIFSTEIN), new Ingredient(20, GRIFFBAND))),
	BIDENAXT_2H("Bidenaxt [2H]", 4600, ÄXTE_2H, new Recipe(1, new Ingredient(13, EISENBARREN), new Ingredient(19, SCHMIEDEOEL))),
	FELSENSPALTER_2H("Felsenspalter [2H]", 7000, ÄXTE_2H, new Recipe(1, new Ingredient(19, EISENBARREN), new Ingredient(29, SCHMIEDEOEL))),
	HELDENAXT_2H("Heldenaxt [2H]", 14200, ÄXTE_2H,
			new Recipe(1, new Ingredient(26, SORANDILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(21, SCHLEIFSTEIN))),
	KAMPFSCHNITTER_2H("Kampfschnitter [2H]", 28500, ÄXTE_2H,
			new Recipe(1, new Ingredient(35, ADAMANTBARREN), new Ingredient(16, SCHMIEDEOEL), new Ingredient(40, SCHLEIFSTEIN))),
	PRUNKAXT_2H("Prunkaxt [2H]", 9300, ÄXTE_2H,
			new Recipe(1, new Ingredient(17, SORANDILBARREN), new Ingredient(3, SCHMIEDEOEL), new Ingredient(14, SCHLEIFSTEIN))),
	SONNENSICHEL_2H("Sonnensichel [2H]", 18700, ÄXTE_2H,
			new Recipe(1, new Ingredient(23, ADAMANTBARREN), new Ingredient(8, SCHMIEDEOEL), new Ingredient(28, SCHLEIFSTEIN))),
	TYRANNENAXT_2H("Tyrannenaxt [2H]", 57300, ÄXTE_2H,
			new Recipe(1, new Ingredient(52, MITHRILBARREN), new Ingredient(6, SCHMIEDEOEL), new Ingredient(8, SCHLEIFSTEIN), new Ingredient(34, GRIFFBAND)));

	public final String ingameName;
	public final int marketValue;
	public final Category category;
	public final Recipe recipe;

	EvergoreItem(String ingameName, int marketValue, Category category, Recipe recipe) {
		this.ingameName = ingameName;
		this.marketValue = marketValue;
		this.category = category;
		this.recipe = recipe;
	}

	public static enum Category {
		ARMBRÜSTE(0.6d, 0.6d),
		ÄXTE(0.6d, 0.6d),
		ÄXTE_2H(0.6d, 0.6d),
		BANDAGEN(0.6d, 0.6d),
		BAUTEILE(0.6d, 0.6d),
		BÖGEN(0.6d, 0.6d),
		DOLCHE(0.6d, 0.6d),
		EDELSTEINE(0, 0.6d),
		ERDSTÄBE(0.6d, 0.6d),
		FEUERSTÄBE(0.6d, 0.6d),
		HANDWERKSMATERIAL(0.6d, 0.6d),
		JAGDBEUTEN(0d, 0.6d),
		KEULEN(0.6d, 0.6d),
		KEULEN_2H(0.6d, 0.6d),
		LEICHTE_RÜSTUNG_LEDER(0.6d, 0.6d),
		LEICHTE_RÜSTUNG_STOFF(0.6d, 0.6d),
		LEICHTE_SCHILDE(0.6d, 0.6d),
		LUFTSTÄBE(0.6d, 0.6d),
		MUNITION_ARMBRÜSTE(0.6d, 0.6d),
		MUNITION_BÖGEN(0.6d, 0.6d),
		MUNITION_MAGIESTÄBE(0.6d, 0.6d),
		ROHSTOFFE(0.6d, 0.6d),
		SCHWERTER(0.6d, 0.6d),
		SCHWERTER_2H(0.6d, 0.6d),
		SCHWERER_SCHILDE(0.6d, 0.6d),
		SCHWERE_RÜSTUNG_METALL(0.6d, 0.6d),
		STANGENWAFFEN_2H(0.6d, 0.6d),
		VERARBEITETE_ROHSTOFFE(0.6d, 0.6d),
		WASSERSTÄBE(0.6d, 0.6d);

		public final double storage;
		public final double withdrawl;

		Category(double storage, double withdrawl) {
			this.storage = storage;
			this.withdrawl = withdrawl;
		}
	}

	public static class Recipe {
		public static final Recipe NOT_CRAFTABLE = new Recipe(0);

		public final int amount;
		public final List<Ingredient> ingredients;

		public Recipe(int amount, Ingredient... ingredients) {
			this.amount = amount;
			this.ingredients = asList(ingredients);
		}
	}

	public static class Ingredient {
		public final int amount;
		public final EvergoreItem item;

		public Ingredient(int amount, EvergoreItem item) {
			this.amount = amount;
			this.item = item;
		}
	}
}
